#!/usr/bin/env node

// These tests primarily ensure that everything works the same in both CJS and ESM modes,
// with both JavaScript and TypeScript.

const ansi        = require("@peteanderson/ansi");
const {spawnSync} = require("node:child_process");

process.chdir(__dirname);

const files = "cj,ct,mj,mt,t".split(",").map(s => `test.${s}s`);

/** @typedef {Record<"env" | "cmd" | "file", string>} ExecInfo */

/** @type {(color: string, file: string) => ExecInfo} */
const execInfo = (color, file) => ({
	env  : `FORCE_COLOR=${color}`,
	cmd  : file.endsWith("js") ? "node" : "npx tsx",
	file
});

const executions = ["", "0", "1", "2", "3"].flatMap(color =>
	files.map(leftFile => execInfo(color, leftFile)).flatMap((left, i) =>
		files.slice(i + 1)
			.map(rightFile => execInfo(color, rightFile))
			.map(right => /** @type const */([left, right]))
	)
);

/** @type {(key: keyof ExecInfo) => [left: number, right: number]} */
const maxOf = key => executions.reduce(
	([lmax, rmax], [l, r]) => [Math.max(lmax, l[key].length), Math.max(rmax, r[key].length)],
	[0, 0],
);

const max = Object.fromEntries(/** @type {const} */(["env", "cmd", "file"]).map(k => [k, maxOf(k)]));

/** @type {(color: boolean, exec: readonly [ExecInfo, ExecInfo]) => string} */
function formatExec(color, exec) {
	const {fg: {green, magenta}} = color ? ansi.ansi : ansi.disabled;
	return exec.map(({env, cmd, file}, index) =>
		magenta("<(") +
		env.padEnd(max.env[index]) + " " +
		ansi.padEnd(green(cmd), max.cmd[index]) + " " +
		ansi.padEnd(file, max.file[index]) +
		magenta(")")
	).join(" ");
}

for (const exec of executions) {
	console.log(`${ansi.fg.green("diff")} ${formatExec(true, exec)}`);

	const proc = spawnSync(`diff ${formatExec(false, exec)}`, {shell: true, stdio : "inherit"});
	if (proc.status)
		process.exit(proc.status);
}

console.log(`\n${ansi.fg.green("node")} test.mjs`);
spawnSync("node", ["test.mjs"], {stdio : "inherit"});